CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(760) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(760),
    LAST_NAME VARCHAR(760),
    PASSWORD VARCHAR(760) NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    CREATED INT,
    UPDATED INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
