CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(700) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(700),
    LAST_NAME VARCHAR(700),
    PASSWORD VARCHAR(700) NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    CREATED INT,
    UPDATED INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
