name: Docker image

on:
  push:
    tags:
      - "v*" # triggers only if push new tag version, like `0.8.4` or else

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build image
      run: |
        make golib
        docker build -t ghcr.io/chesscomputing/authz:${GITHUB_REF##*/} .
#         docker build --build-arg srv=Authz --build-arg tag=${GITHUB_REF##*/} -t ghcr.io/chesscomputing/authz ../golib/k8s

    - name: Login to ghcr.io registry
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${GITHUB_REF##*/}
