name: Docker image

on:
  push:
    tags:
      - "v*" # triggers only if push new tag version, like `0.8.4` or else

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # https://github.com/orgs/community/discussions/26686
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

#     - name: Echo
#       run: |
#         echo ${{ steps.branch_name.outputs.SOURCE_NAME }}
#         echo ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
#         echo ${{ steps.branch_name.outputs.SOURCE_TAG }}

    - name: Build image
      run: |
        make golib
        docker build -t ghcr.io/chesscomputing/authz:${{ steps.branch_name.outputs.SOURCE_TAG }}

    - name: Login to ghcr.io registry
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/chesscomputing/authz:latest
          ghcr.io/chesscomputing/authz:${{ steps.branch_name.outputs.SOURCE_TAG }}
